### ISSUE TITLE
File progress

### ISSUE THREAD

**Issue by galaxyhaxz** [galaxyhaxz/morkvacker#1]
- [x] APPFAT.CPP
- [x] AUTOMAP.CPP
- [x] CONTROL.CPP
- [x] CURSOR.CPP
- [x] CURSOR.H
- [x] DEBUG.CPP
- [x] DIABLO.CPP
- [x] DIABLO.H
- [x] DIABLO.RC
- [x] DIABLOUI.H
- [x] DOOM.CPP
- [x] DOOM.H
- [x] DRLG_L1.CPP
- [x] DRLG_L1.H
- [x] DRLG_L2.CPP
- [x] DRLG_L3.CPP
- [x] EFFECTS.CPP
- [x] EFFECTS.H
- [x] ENGINE.CPP
- [x] ERROR.CPP
- [x] ERROR.H
- [x] GAMEMENU.CPP
- [x] GENDUNG.CPP
- [x] GENDUNG.H
- [x] GMENU.CPP
- [x] HELP.CPP
- [x] ICON1.ICO
- [x] INIT.CPP
- [x] INTERFAC.CPP
- [x] INV.CPP
- [x] INV.H
- [x] ITEMDAT.CPP
- [x] ITEMDAT.H
- [x] ITEMS.CPP
- [x] ITEMS.H
- [x] LIGHTING.CPP
- [x] LOADSAVE.CPP
- [x] MAINMENU.CPP
- [x] MINITEXT.CPP
- [x] MISDAT.CPP
- [x] MISDAT.H
- [x] MISSILES.CPP
- [x] MISSILES.H
- [x] MONSTDAT.CPP
- [x] MONSTDAT.H
- [x] MONSTER.CPP
- [x] MONSTER.H
- [x] MPQAPI.CPP
- [x] MSG.CPP
- [x] MSG.H
- [x] MULTI.CPP
- [x] NTHREAD.CPP
- [x] OBJDAT.CPP
- [x] OBJDAT.H
- [x] OBJECTS.CPP
- [x] OBJECTS.H
- [x] PACKPLR.CPP
- [x] PACKPLR.H
- [x] PALETTE.CPP
- [x] PALETTE.H
- [x] PFILE.CPP
- [x] PLAYER.CPP
- [x] PLAYER.H
- [x] PORTAL.CPP
- [x] PORTAL.H
- [x] QUESTS.CPP
- [x] QUESTS.H
- [x] SCROLLRT.CPP
- [x] SCROLLRT.H
- [x] SOUND.CPP
- [x] SOUND.H
- [x] SPELLDAT.CPP
- [x] SPELLS.CPP
- [x] SPELLS.H
- [x] STORES.CPP
- [x] STORES.H
- [x] SYNC.CPP
- [x] TEXTDAT.CPP
- [x] TEXTDAT.H
- [x] TOWN.CPP
- [x] TOWNERS.CPP
- [x] TOWNERS.H
- [x] TRIGS.CPP
- [x] TRIGS.H
- [x] WAVE.CPP

**Comment by mewmew** [comment]
Very exciting progress!

**Comment by mewmew** [comment]
Wow, only the behemoths are still standing.

![Infernal Behemoth](https://upload.wikimedia.org/wikipedia/commons/3/36/Dictionnaire_Infernal_-_Behemoth.jpg)

**Comment by galaxyhaxz** [comment]
That is one pregnancy belly ;P
